version: 0.2

phases:
  install: 
    runtime-versions:
      php: 7.2
  pre_build: # commands to be run before build
    commands:

  build:
    commands:
    - echo Build started on `date`

    - echo installing composer...
    - composer install --optimize-autoloader --no-dev

    - echo installing node packages...
    - npm install

    - echo creating .env file...
    - cp .env.example .env

    - echo generating app key
    - php artisan key:generate

    - echo Optimizing Configuration Loading
    - php artisan config:cache

    - echo Optimizing Route Loading
    - php artisan route:cache

  post_build:
    commands:
      - echo Build completed on `date`